const $=id=>document.getElementById(id);let CATALOG=[];
// GitHub Pages mode: the site is static, so field data is stored locally on the device.
const STATIC_MODE = location.hostname.endsWith('github.io');
const LS_KEY='asaslab_field_v32';
function localDB(){let d=JSON.parse(localStorage.getItem(LS_KEY)||'null');if(!d)d={visits:[],catalog:[],projects:[],samples:[],tests:[],reports:[],clients:[],equipment:[],audit:[]};if(!d.catalog.length)d.catalog=[
 {id:1,code:'D1883',name_ar:'نسبة تحمل كاليفورنيا CBR',name_en:'California Bearing Ratio',category:'تربة',standard:'ASTM D1883',version:'2024'},
 {id:2,code:'D2216',name_ar:'محتوى الرطوبة',name_en:'Water Content',category:'تربة',standard:'ASTM D2216',version:'2019'},
 {id:3,code:'D4318',name_ar:'حدود أتربرج',name_en:'Atterberg Limits',category:'تربة',standard:'ASTM D4318',version:'2018'},
 {id:4,code:'C136',name_ar:'التحليل المنخلي',name_en:'Sieve Analysis',category:'ركام',standard:'ASTM C136',version:'2019'},
 {id:5,code:'D1557',name_ar:'بروكتور المعدل',name_en:'Modified Proctor',category:'تربة',standard:'ASTM D1557',version:'2021'},
 {id:6,code:'D698',name_ar:'بروكتور القياسي',name_en:'Standard Proctor',category:'تربة',standard:'ASTM D698',version:'2021'},
 {id:7,code:'C39',name_ar:'مقاومة الضغط للخرسانة',name_en:'Compressive Strength',category:'خرسانة',standard:'ASTM C39',version:'2024'},
 {id:8,code:'C143',name_ar:'اختبار الهطول',name_en:'Slump',category:'خرسانة',standard:'ASTM C143',version:'2020'},
 {id:9,code:'D2041',name_ar:'الوزن النوعي الأقصى للخلطة الإسفلتية Gmm',name_en:'Maximum Specific Gravity',category:'أسفلت',standard:'ASTM D2041',version:'2022'},
 {id:10,code:'D6132',name_ar:'سماكة الطلاء الجاف DFT',name_en:'Dry Film Thickness',category:'طلاءات',standard:'ASTM D6132',version:'2022'},
 {id:11,code:'D7091',name_ar:'قياس السماكة الجافة للطلاءات',name_en:'Dry Film Thickness',category:'طلاءات',standard:'ASTM D7091',version:'2022'},
 {id:12,code:'ROAD-PROFILER',name_ar:'بروفايل الطريق',name_en:'Road Profiler',category:'طرق',standard:'Road Profiler',version:'1.0'},
 {id:13,code:'GRB-ROUGHNESS',name_ar:'وعورة الأسفلت',name_en:'Asphalt Roughness',category:'طرق',standard:'GRB',version:'1.0'}];localStorage.setItem(LS_KEY,JSON.stringify(d));return d}
function saveDB(d){localStorage.setItem(LS_KEY,JSON.stringify(d));return d}
function now(){return new Date().toLocaleString('ar-SA')}
function staticApi(path,opt={}){let d=localDB(), body={};try{body=opt.body?JSON.parse(opt.body):{}}catch{};
 if(path==='/api/login')return body.username==='admin'&&body.password==='1234'?{user:{full_name:'مدير النظام',role:'admin',username:'admin'}}:{error:'اسم المستخدم أو كلمة المرور غير صحيحة'};
 if(path==='/api/logout'){localStorage.removeItem('asaslab_session');return {ok:true}};
 if(path==='/api/catalog')return d.catalog;
 if(path.startsWith('/api/field/search')){let no=decodeURIComponent((path.split('license=')[1]||''));return d.visits.filter(x=>x.license_no===no).slice(-1)}
 if(path==='/api/field/visits'){let id=(d.visits.length?Math.max(...d.visits.map(x=>x.id)):0)+1;let x={...body,id,created_at:now(),full_name:'مدير النظام'};d.visits.push(x);d.audit.push({created_at:now(),full_name:'مدير النظام',action:'حفظ زيارة ميدانية',entity:'field_visit',details:`رقم ${id}`});saveDB(d);return {id}}
 if(path==='/api/field/recent')return d.visits.slice().reverse().slice(0,20);
 if(path==='/api/field/status'){let x=d.visits.find(v=>v.id===+body.id);if(!x)return {error:'الزيارة غير موجودة'};x.status=body.status;x.updated_at=now();d.audit.push({created_at:now(),full_name:'مدير النظام',action:'تغيير حالة الزيارة',entity:'field_visit',details:`${x.id}: ${body.status}`});saveDB(d);return {ok:true}}
 if(path==='/api/dashboard'){return {counts:{projects:d.projects.length,samples:d.samples.length,tests:d.tests.length,reports:d.reports.length,equipment:d.equipment.length,field_visits:d.visits.length},activity:d.audit.slice(-10).reverse(),clients:d.clients,projects:d.projects,samples:d.samples,tests:d.tests,reports:d.reports,equipment:d.equipment,audit:d.audit.slice().reverse()}}
 if(path.startsWith('/api/report/')){let id=+path.split('/').pop(),r=d.reports.find(x=>x.test_id===id)||{};return {...r,data:{inputs:r.inputs||{},results:r.results||{}} ,lab_name:'مختبر أساس'}}
 if(path==='/api/clients'||path==='/api/projects'||path==='/api/samples'||path==='/api/equipment'){let map={'/api/clients':'clients','/api/projects':'projects','/api/samples':'samples','/api/equipment':'equipment'},k=map[path];let id=d[k].length+1;d[k].push({...body,id,created_at:now(),code:k==='projects'?`PRJ-${String(id).padStart(4,'0')}`:undefined});saveDB(d);return {id}}
 if(path==='/api/tests/proctor'||path==='/api/tests/generic'){let id=d.tests.length+1;let code=body.standard_code||'TEST';let cat=d.catalog.find(x=>x.code===code)||d.catalog[0];let test_no=body.test_no||`T-${String(id).padStart(5,'0')}`;d.tests.push({id,test_no,sample_id:body.sample_id||'',name_ar:cat.name_ar,code:cat.code,standard:cat.standard,status:'مسودة',mdd:body.mdd,omc:body.omc});let report_no=`R-${new Date().getFullYear()}-${String(id).padStart(5,'0')}`;d.reports.push({id,report_no,test_id:id,name_ar:cat.name_ar,status:'مسودة',issued_at:now(),inputs:body.inputs||{},results:body.results||{mdd:body.mdd,omc:body.omc}});saveDB(d);return {report_no}}
 if(path==='/api/users')return [{id:1,username:'admin',full_name:'مدير النظام',role:'admin',active:1,created_at:'—'}];
 return []}
async function api(path,opt={}){if(STATIC_MODE){try{return staticApi(path,opt)}catch(e){throw Error(e.message||'خطأ')}}try{let r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});if(r.status===401){location.reload();return null}let j=await r.json();if(!r.ok)throw Error(j.error||'خطأ');return j}catch(e){throw e}}
async function login(){try{let j=await api('/api/login',{method:'POST',body:JSON.stringify({username:$('lu').value,password:$('lp').value})});$('login').classList.add('hidden');$('app').classList.remove('hidden');$('me').textContent=j.user.full_name+' — '+roleName(j.user.role);if(j.user.role!=='admin')$('usersNav')?.classList.add('hidden');await loadCatalog();load()}catch(e){alert(e.message)}}
async function logout(){await fetch('/api/logout',{method:'POST'});location.reload()}
document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>go(b.dataset.p));function go(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(p).classList.add('active');$('title').textContent=document.querySelector('[data-p="'+p+'"]').textContent;side.classList.remove('open');load()}
async function loadCatalog(){CATALOG=await api('/api/catalog');renderCatalog()}
function renderCatalog(){if(!$('catalogRows'))return;let q=($('catSearch')?.value||'').toLowerCase();$('catalogRows').innerHTML=CATALOG.filter(x=>(x.code+' '+x.name_ar+' '+x.standard+' '+x.category).toLowerCase().includes(q)).map(x=>`<tr><td>${x.code}</td><td>${x.name_ar}<br><span class=muted>${x.name_en||''}</span></td><td>${x.category}</td><td>${x.standard}</td><td>${x.version||'—'}</td></tr>`).join('')}
function show(t){let b='';if(t==='client')b='<h2>إضافة عميل</h2><input id=name placeholder="اسم العميل"><input id=phone placeholder="الهاتف"><input id=email placeholder="البريد"><button class=btn onclick=saveClient()>حفظ</button>';
if(t==='project')b='<h2>إضافة مشروع</h2><input id=name placeholder="اسم المشروع"><input id=client_id placeholder="رقم العميل (اختياري)"><input id=location placeholder="الموقع"><button class=btn onclick=saveProject()>حفظ</button>';
if(t==='sample')b='<h2>تسجيل عينة</h2><input id=sample_no placeholder="رقم العينة"><input id=project_id placeholder="رقم المشروع (اختياري)"><select id=material><option>تربة</option><option>ركام</option><option>خرسانة</option><option>أسفلت</option><option>طلاءات</option><option>مواد بناء</option><option>مواسير</option></select><input id=source placeholder="مصدر العينة"><input id=received_date type=date value="'+new Date().toISOString().slice(0,10)+'"><textarea id=notes placeholder="ملاحظات"></textarea><button class=btn onclick=saveSample()>حفظ</button>';
if(t==='equipment')b='<h2>إضافة جهاز</h2><input id=ename placeholder="اسم الجهاز"><input id=serial placeholder="Serial Number"><input id=manufacturer placeholder="الشركة المصنعة"><input id=model placeholder="الموديل"><div class=grid><input id=last type=date><input id=next type=date></div><input id=certificate_no placeholder="رقم شهادة المعايرة"><textarea id=enotes placeholder="ملاحظات"></textarea><button class=btn onclick=saveEquipment()>حفظ</button>';
if(t==='test')b=testChooser();$('modalBody').innerHTML=b;$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
async function saveClient(){await api('/api/clients',{method:'POST',body:JSON.stringify({name:name.value,phone:phone.value,email:email.value})});closeModal();load()}
async function saveProject(){await api('/api/projects',{method:'POST',body:JSON.stringify({name:name.value,client_id:client_id.value||null,location:location.value})});closeModal();load()}
async function saveSample(){await api('/api/samples',{method:'POST',body:JSON.stringify({sample_no:sample_no.value,project_id:project_id.value||null,material:material.value,source:source.value,received_date:received_date.value,notes:notes.value})});closeModal();load()}
async function saveEquipment(){await api('/api/equipment',{method:'POST',body:JSON.stringify({name:ename.value,serial_no:serial.value,manufacturer:manufacturer.value,model:model.value,last_calibration:last.value,next_calibration:next.value,certificate_no:certificate_no.value,notes:enotes.value})});closeModal();load()}
function testChooser(){return `<h2>إضافة اختبار</h2><label>نوع الاختبار</label><select id=cat onchange=buildTestForm()><option value="">اختر الاختبار...</option>${CATALOG.map(x=>`<option value="${x.id}">${x.code} — ${x.name_ar} — ${x.standard}</option>`).join('')}</select><div id=testForm></div>`}
function buildTestForm(){let cat=CATALOG.find(x=>String(x.id)==cat.value);if(!cat){testForm.innerHTML='';return}if(cat.code==='D1557'||cat.code==='D698'){testForm.innerHTML=proctorForm(cat.code);return}testForm.innerHTML=genericForm(cat)}
function genericForm(cat){let fields=[];const map={D1883:[['cbr254','CBR عند 2.54 mm','%'],['cbr508','CBR عند 5.08 mm','%'],['swelling','الانتفاخ','%']],D2216:[['wet_mass','وزن العينة الرطبة','g'],['dry_mass','وزن العينة الجافة','g']],D4318:[['LL','حد السيولة LL','%'],['PL','حد اللدونة PL','%'],['PI','مؤشر اللدونة PI','%']],C136:[['sample_mass','كتلة العينة','g'],['FM','معامل النعومة',''],['nominal_size','المقاس الاسمي الأقصى','mm']],C135:[['sample_mass','كتلة العينة','g'],['FM','معامل النعومة','']],C39:[['load','الحمل الأقصى','kN'],['area','مساحة المقطع','mm²'],['strength','مقاومة الضغط','MPa']],C143:[['slump','الهبوط','mm']],D2041:[['mass_dry','كتلة العينة الجافة','g'],['mass_submerged','الكتلة المغمورة','g'],['Gmm','Gmm','']],D6132:[['DFT_avg','متوسط السماكة الجافة DFT','µm']],D7091:[['DFT_avg','متوسط السماكة','µm']],['ROAD-PROFILER']:[['IRI','IRI','m/km'],['roughness','وعورة الطريق',''],['distance','المسافة','km']],['GRB-ROUGHNESS']:[['roughness','وعورة الأسفلت','']],['CARBONATION']:[['depth','عمق الكربنة','mm']],['ULTRASONIC']:[['velocity','سرعة النبضة','km/s']],['REBAR-CORROSION']:[['potential','جهد التآكل','mV']],['BITUMEN-MCI-RC2']:[['rate','معدل الرش','L/m²']],['GMP']:[['Gmb','Gmb',''],['density','الكثافة','kg/m³'],['air_voids','الفراغات الهوائية','%']]};let a=map[cat.code]||[['result','النتيجة','']];for(const [id,n,u] of a)fields.push(`<label>${n}${u?' ('+u+')':''}<input id=f_${id} type="number" step="any"></label>`);return `<div class=test-fields><input id=test_no placeholder="رقم الاختبار"><input id=sample_id placeholder="معرف العينة"><input id=started_at type=datetime-local>${fields.join('')}</div><p class=muted>${cat.standard} — ${cat.name_ar}. الحقول قابلة للتخصيص حسب إجراء المختبر.</p><button class=btn onclick="saveGeneric('${cat.id}','${cat.code}')">حفظ الاختبار</button><div id=genericResult></div>`}
function proctorForm(code){let r='';for(let i=1;i<=5;i++)r+=`<tr><td>${i}</td><td><input id=w${i} type=number step=.01></td><td><input id=wet${i} type=number step=.1></td></tr>`;return `<h3>${code==='D1557'?'ASTM D1557 — Modified Proctor':'ASTM D698 — Standard Proctor'}</h3><div class=test-fields><input id=test_no placeholder="رقم الاختبار"><input id=sample_id placeholder="معرف العينة"><input id=mold_weight type=number placeholder="وزن القالب g"><input id=mold_volume type=number value="944" placeholder="حجم القالب cm³"></div><table><thead><tr><th>النقطة</th><th>الرطوبة %</th><th>القالب + التربة الرطبة g</th></tr></thead><tbody>${r}</tbody></table><button class=btn onclick="calcProctor('${code}')">حساب وحفظ</button><div id=presult></div>`}
async function calcProctor(code){let pts=[];let mw=+mold_weight.value,mv=+mold_volume.value;for(let i=1;i<=5;i++){let w=+document.getElementById('w'+i).value,wt=+document.getElementById('wet'+i).value;if(w>=0&&wt>mw&&mv>0){let wd=(wt-mw)/mv;pts.push({moisture:w,mold_soil_wet:wt,wet_density:wd,dry_density:wd/(1+w/100)})}}if(pts.length<2)return alert('أدخل نقطتين على الأقل');let best=pts.reduce((a,b)=>b.dry_density>a.dry_density?b:a);let j=await api('/api/tests/proctor',{method:'POST',body:JSON.stringify({test_no:test_no.value,sample_id:sample_id.value,mdd:best.dry_density,omc:best.moisture,points:pts,standard_code:code})});presult.innerHTML=`<div class=result>تم الحفظ<br>MDD = <b>${best.dry_density.toFixed(3)} g/cm³</b><br>OMC = <b>${best.moisture.toFixed(2)}%</b><br>التقرير: ${j.report_no}</div>`;load()}
async function saveGeneric(id,code){let inputs={};let results={};document.querySelectorAll('[id^=f_]').forEach(x=>{if(x.value!=='')results[x.id.slice(2)]=x.value});let d={catalog_id:+id,test_no:test_no.value,sample_id:sample_id.value,started_at:started_at.value,inputs,results};let j=await api('/api/tests/generic',{method:'POST',body:JSON.stringify(d)});genericResult.innerHTML=`<div class=result>تم حفظ ${code}<br>رقم التقرير: <b>${j.report_no}</b></div>`;load()}
async function load(){let j=await api('/api/dashboard');if(!j)return;cProjects.textContent=j.counts.projects;cSamples.textContent=j.counts.samples;cTests.textContent=j.counts.tests;cReports.textContent=j.counts.reports;cEquipment.textContent=j.counts.equipment;cFieldVisits.textContent=j.counts.field_visits||0;activity.innerHTML=j.activity.map(x=>`<div>${x.created_at} — ${x.action} — ${x.details||''}</div>`).join('');clients.innerHTML=j.clients.map(x=>`<tr><td>${x.name}</td><td>${x.phone||''}</td><td>${x.email||''}</td></tr>`).join('');projects.innerHTML=j.projects.map(x=>`<tr><td>${x.code}</td><td>${x.name}</td><td>${x.client_name||''}</td><td>${x.location||''}</td><td>${x.status}</td></tr>`).join('');samples.innerHTML=j.samples.map(x=>`<tr><td>${x.sample_no}</td><td>${x.project_name||''}</td><td>${x.material}</td><td>${x.received_date}</td><td>${x.status}</td></tr>`).join('');tests.innerHTML=j.tests.map(x=>`<tr><td>${x.test_no}</td><td>${x.sample_no}</td><td>${x.name_ar}<br><span class=muted>${x.code}</span></td><td>${x.standard}</td><td>${x.mdd!=null?'MDD '+(+x.mdd).toFixed(3)+' / OMC '+(+x.omc).toFixed(2)+'%':'—'}</td><td>${x.status}</td></tr>`).join('');reports.innerHTML=j.reports.map(x=>`<tr><td>${x.report_no}</td><td>${x.name_ar}</td><td>${x.status}</td><td>${x.issued_at||''}</td><td><button class=btn onclick="printReport(${x.test_id})">طباعة</button></td></tr>`).join('');equipment.innerHTML=j.equipment.map(x=>`<tr><td>${x.name}</td><td>${x.serial_no||''}</td><td>${x.last_calibration||''}</td><td>${x.next_calibration||''}</td><td>${x.certificate_no||''}</td><td>${x.status}</td></tr>`).join('');audit.innerHTML=j.audit.map(x=>`<tr><td>${x.created_at}</td><td>${x.full_name||''}</td><td>${x.action}</td><td>${x.entity||''}</td><td>${x.details||''}</td></tr>`).join('')}
async function printReport(id){let j=await api('/api/report/'+id);let w=open('','_blank');let inputs=Object.entries(j.data.inputs||{}).map(([k,v])=>`<tr><th>${k}</th><td>${v}</td></tr>`).join('');let results=Object.entries(j.data.results||{}).map(([k,v])=>`<tr><th>${k}</th><td>${v}</td></tr>`).join('');w.document.write(`<html dir=rtl><head><title>${j.report_no}</title><style>body{font-family:Tahoma;padding:35px}table{width:100%;border-collapse:collapse;margin:15px 0}td,th{border:1px solid #888;padding:8px;text-align:right}h1,h2{text-align:center}</style></head><body><h1>${j.lab_name}</h1><h2>تقرير اختبار</h2><table><tr><th>رقم التقرير</th><td>${j.report_no}</td></tr><tr><th>رقم الاختبار</th><td>${j.test_no}</td></tr><tr><th>العينة</th><td>${j.sample_no}</td></tr><tr><th>الاختبار</th><td>${j.name_ar}</td></tr><tr><th>المعيار</th><td>${j.standard}</td></tr></table><h3>المدخلات</h3><table>${inputs||'<tr><td>—</td></tr>'}</table><h3>النتائج</h3><table>${results||'<tr><td>—</td></tr>'}</table><p>الحالة: ${j.status}</p><script>print()<\/script></body></html>`);w.document.close()}
(async()=>{try{await loadCatalog()}catch(e){}})();

let fieldTests=[]; let fieldLat=null, fieldLng=null;
function initField(){renderFieldTests();loadFieldRecent();$('f_photos')?.addEventListener('change',previewPhotos);}
function addFieldTest(){if(fieldTests.length>=4)return alert('الحد الأقصى 4 اختبارات في نفس الزيارة');fieldTests.push({name:'',standard:'',result:''});renderFieldTests();}
function renderFieldTests(){const el=$('fieldTests');if(!el)return;el.innerHTML=fieldTests.map((t,i)=>`<div class="field-test-row"><b>الاختبار ${i+1}</b><input value="${t.name}" placeholder="اسم الاختبار" oninput="fieldTests[${i}].name=this.value"><input value="${t.standard}" placeholder="المعيار / ASTM" oninput="fieldTests[${i}].standard=this.value"><input value="${t.result}" placeholder="النتيجة / القراءات" oninput="fieldTests[${i}].result=this.value"><button class="danger small" onclick="fieldTests.splice(${i},1);renderFieldTests()">حذف</button></div>`).join('');}
async function searchLicense(){const no=$('f_license').value.trim();if(!no)return alert('أدخل رقم الرخصة');try{const rows=await api('/api/field/search?license='+encodeURIComponent(no));if(rows.length){const x=rows[0];$('f_contractor').value=x.contractor_name||'';$('f_project').value=x.project_name||'';$('f_sector').value=x.sector_name||'';$('f_layer').value=x.layer_no||'';$('f_location').value=x.location||'';fieldMsg.innerHTML='<div class="result">تم العثور على بيانات سابقة للرخصة</div>';}else{fieldMsg.innerHTML='<div class="muted">لا توجد بيانات سابقة؛ أكمل البيانات يدويًا.</div>';}}catch(e){alert(e.message)}}
function getLocation(){if(!navigator.geolocation)return alert('GPS غير متاح في هذا المتصفح');navigator.geolocation.getCurrentPosition(p=>{fieldLat=p.coords.latitude;fieldLng=p.coords.longitude;$('gpsStatus').textContent=`تم تحديد الموقع: ${fieldLat.toFixed(6)}, ${fieldLng.toFixed(6)}`;},e=>alert('تعذر تحديد الموقع: '+e.message),{enableHighAccuracy:true,timeout:10000});}
function previewPhotos(e){const el=$('photoPreview');el.innerHTML='';[...e.target.files].forEach(f=>{const img=document.createElement('img');img.src=URL.createObjectURL(f);el.appendChild(img);});}
async function saveFieldVisit(){const license=$('f_license').value.trim();if(!license)return alert('رقم الرخصة مطلوب');const d={license_no:license,contractor_name:$('f_contractor').value,project_name:$('f_project').value,sector_name:$('f_sector').value,layer_no:$('f_layer').value,location:$('f_location').value,latitude:fieldLat,longitude:fieldLng,project_id:$('f_project_id').value||null,sample_id:$('f_sample_id').value||null,tests:fieldTests,notes:$('f_notes').value,status:'مسودة'};try{const j=await api('/api/field/visits',{method:'POST',body:JSON.stringify(d)});$('fieldMsg').innerHTML=`<div class="result">تم حفظ الزيارة بنجاح — رقم ${j.id}</div>`;loadFieldRecent();}catch(e){alert(e.message)}}
async function loadFieldRecent(){try{const rows=await api('/api/field/recent');if(!$('fieldRecent'))return;$('fieldRecent').innerHTML=rows.map(x=>`<div class="recent-item"><b>${x.license_no}</b> — ${x.contractor_name||''}<br>${x.project_name||''} — ${x.layer_no||''}<br><span class="muted">الحالة: ${x.status} | ${x.created_at} — ${x.full_name||''}</span><br><button class="btn small" onclick="setFieldStatus(${x.id},'مرسلة')">إرسال</button> <button class="btn small" onclick="setFieldStatus(${x.id},'قيد المراجعة')">مراجعة</button> <button class="btn small" onclick="setFieldStatus(${x.id},'معتمدة')">اعتماد</button> <button class="danger small" onclick="setFieldStatus(${x.id},'مرفوضة')">رفض</button></div>`).join('')||'<div class="muted">لا توجد زيارات بعد.</div>';}catch(e){}}
const _oldGo=go;go=function(p){_oldGo(p);if(p==='field'){fieldUser.textContent=$('me').textContent;initField();}};

async function setFieldStatus(id,status){try{await api('/api/field/status',{method:'POST',body:JSON.stringify({id,status})});loadFieldRecent();load()}catch(e){alert(e.message)}}
function showUserForm(){
  $('modalBody').innerHTML=`<h2>إضافة مستخدم</h2><div class="test-fields"><input id="u_username" placeholder="اسم المستخدم"><input id="u_full_name" placeholder="الاسم الكامل"><input id="u_password" type="password" placeholder="كلمة المرور (4 أحرف على الأقل)"><select id="u_role"><option value="technician">فني مختبر</option><option value="field">مفتش ميداني</option><option value="manager">مدير</option><option value="admin">مدير نظام</option></select></div><button class="btn" onclick="createUser()">حفظ المستخدم</button>`;$('modal').classList.add('show');}
async function createUser(){try{await api('/api/users/create',{method:'POST',body:JSON.stringify({username:$('u_username').value,full_name:$('u_full_name').value,password:$('u_password').value,role:$('u_role').value})});closeModal();loadUsers();}catch(e){alert(e.message)}}
async function loadUsers(){if(!$('usersRows'))return;try{const rows=await api('/api/users');$('usersRows').innerHTML=rows.map(x=>`<tr><td>${x.username}</td><td>${x.full_name}</td><td>${roleName(x.role)}</td><td>${x.active?'نشط':'موقوف'}</td><td>${x.created_at}</td><td><button class="btn small" onclick='editUser(${JSON.stringify(x)})'>تعديل</button></td></tr>`).join('')}catch(e){$('usersRows').innerHTML='<tr><td colspan="6">ليس لديك صلاحية عرض المستخدمين</td></tr>'}}
function roleName(r){return ({admin:'مدير نظام',manager:'مدير',technician:'فني مختبر',field:'مفتش ميداني'})[r]||r}
function editUser(x){$('modalBody').innerHTML=`<h2>تعديل المستخدم: ${x.username}</h2><div class="test-fields"><input id="eu_full_name" value="${x.full_name||''}" placeholder="الاسم الكامل"><select id="eu_role"><option value="technician" ${x.role==='technician'?'selected':''}>فني مختبر</option><option value="field" ${x.role==='field'?'selected':''}>مفتش ميداني</option><option value="manager" ${x.role==='manager'?'selected':''}>مدير</option><option value="admin" ${x.role==='admin'?'selected':''}>مدير نظام</option></select><input id="eu_password" type="password" placeholder="كلمة مرور جديدة (اختياري)"><label><input id="eu_active" type="checkbox" ${x.active?'checked':''}> الحساب نشط</label></div><button class="btn" onclick="updateUser(${x.id})">حفظ التعديل</button>`;$('modal').classList.add('show')}
async function updateUser(id){try{await api('/api/users/update',{method:'POST',body:JSON.stringify({id,full_name:$('eu_full_name').value,role:$('eu_role').value,password:$('eu_password').value,active:$('eu_active').checked})});closeModal();loadUsers()}catch(e){alert(e.message)}}
const _load0=load;load=async function(){await _load0();if($('usersRows'))loadUsers();};
